import type { Match, Promotion, ActiveBet, Transaction, Notification, AdminStats } from "./constants";
import { HERO_SLIDE_BACKGROUNDS } from "@/lib/hero-assets";

const teams = {
  manCity: { id: "mci", name: "Manchester City", shortName: "MCI", logo: "🔵" },
  liverpool: { id: "liv", name: "Liverpool", shortName: "LIV", logo: "🔴" },
  realMadrid: { id: "rm", name: "Real Madrid", shortName: "RMA", logo: "⚪" },
  barcelona: { id: "bar", name: "Barcelona", shortName: "BAR", logo: "🔵🔴" },
  bayern: { id: "bay", name: "Bayern Munich", shortName: "BAY", logo: "🔴" },
  dortmund: { id: "bvb", name: "Dortmund", shortName: "BVB", logo: "🟡" },
  lakers: { id: "lal", name: "LA Lakers", shortName: "LAL", logo: "💜" },
  celtics: { id: "bos", name: "Boston Celtics", shortName: "BOS", logo: "🍀" },
  warriors: { id: "gsw", name: "Golden State", shortName: "GSW", logo: "💛" },
  nets: { id: "bkn", name: "Brooklyn Nets", shortName: "BKN", logo: "⚫" },
  djokovic: { id: "djo", name: "Djokovic", shortName: "DJO", logo: "🎾" },
  alcaraz: { id: "alc", name: "Alcaraz", shortName: "ALC", logo: "🎾" },
  india: { id: "ind", name: "India", shortName: "IND", logo: "🇮🇳" },
  australia: { id: "aus", name: "Australia", shortName: "AUS", logo: "🇦🇺" },
  navi: { id: "navi", name: "NAVI", shortName: "NAVI", logo: "🎮" },
  faze: { id: "faze", name: "FaZe Clan", shortName: "FAZE", logo: "🔴" },
  arsenal: { id: "ars", name: "Arsenal", shortName: "ARS", logo: "🔴" },
  chelsea: { id: "che", name: "Chelsea", shortName: "CHE", logo: "🔵" },
  inter: { id: "int", name: "Inter Milan", shortName: "INT", logo: "🔵⚫" },
  acMilan: { id: "mil", name: "AC Milan", shortName: "MIL", logo: "🔴⚫" },
};

export const mockMatches: Match[] = [
  {
    id: "m1",
    homeTeam: teams.manCity,
    awayTeam: teams.liverpool,
    league: "Premier League",
    leagueId: "epl",
    sport: "football",
    startTime: new Date(Date.now() + 3600000),
    isLive: true,
    liveMinute: 67,
    homeScore: 2,
    awayScore: 1,
    odds: { home: 1.85, draw: 3.40, away: 4.20 },
    stats: { possession: [58, 42], shots: [14, 8], corners: [6, 3] },
  },
  {
    id: "m2",
    homeTeam: teams.realMadrid,
    awayTeam: teams.barcelona,
    league: "La Liga",
    leagueId: "laliga",
    sport: "football",
    startTime: new Date(Date.now() + 7200000),
    isLive: false,
    odds: { home: 2.10, draw: 3.25, away: 3.50 },
  },
  {
    id: "m3",
    homeTeam: teams.lakers,
    awayTeam: teams.celtics,
    league: "NBA",
    leagueId: "nba",
    sport: "basketball",
    startTime: new Date(Date.now() + 1800000),
    isLive: true,
    liveMinute: 32,
    homeScore: 78,
    awayScore: 82,
    odds: { home: 1.95, away: 1.90 },
  },
  {
    id: "m4",
    homeTeam: teams.bayern,
    awayTeam: teams.dortmund,
    league: "Bundesliga",
    leagueId: "bundesliga",
    sport: "football",
    startTime: new Date(Date.now() + 5400000),
    isLive: false,
    odds: { home: 1.65, draw: 3.80, away: 5.00 },
  },
  {
    id: "m5",
    homeTeam: teams.djokovic,
    awayTeam: teams.alcaraz,
    league: "ATP Masters",
    leagueId: "atp",
    sport: "tennis",
    startTime: new Date(Date.now() + 900000),
    isLive: true,
    liveMinute: 2,
    homeScore: 1,
    awayScore: 0,
    odds: { home: 2.30, away: 1.65 },
  },
  {
    id: "m6",
    homeTeam: teams.arsenal,
    awayTeam: teams.chelsea,
    league: "Premier League",
    leagueId: "epl",
    sport: "football",
    startTime: new Date(Date.now() + 86400000),
    isLive: false,
    odds: { home: 2.05, draw: 3.30, away: 3.60 },
  },
  {
    id: "m7",
    homeTeam: teams.inter,
    awayTeam: teams.acMilan,
    league: "Serie A",
    leagueId: "seriea",
    sport: "football",
    startTime: new Date(Date.now() + 10800000),
    isLive: false,
    odds: { home: 2.20, draw: 3.10, away: 3.25 },
  },
  {
    id: "m8",
    homeTeam: teams.navi,
    awayTeam: teams.faze,
    league: "CS2 Major",
    leagueId: "cs2",
    sport: "esports",
    startTime: new Date(Date.now() + 2700000),
    isLive: true,
    liveMinute: 15,
    homeScore: 1,
    awayScore: 0,
    odds: { home: 1.75, away: 2.05 },
  },
];

export const mockPromotions: Promotion[] = [
  {
    id: "p1",
    title: "Welcome Bonus",
    description: "Get 100% match on your first deposit up to GH₵ 500.00",
    image: "/images/promotions/welcome.svg",
    cta: "Claim Now",
    badge: "NEW",
  },
  {
    id: "p2",
    title: "Acca Insurance",
    description: "Get your stake back if one leg lets you down on 5+ fold accumulators",
    image: "/images/promotions/acca.svg",
    cta: "Learn More",
  },
  {
    id: "p3",
    title: "Live Boost",
    description: "Enhanced odds on selected live matches every weekend",
    image: "/images/promotions/default.svg",
    cta: "View Boosts",
    badge: "HOT",
  },
  {
    id: "p4",
    title: "Refer a Friend",
    description: "Earn GH₵ 50.00 for every friend who joins and places their first bet",
    image: "/images/promotions/refer.svg",
    cta: "Refer Now",
  },
];

export const mockActiveBets: ActiveBet[] = [
  {
    id: "b1",
    type: "single",
    selections: [
      {
        id: "s1",
        matchId: "m1",
        matchName: "Man City vs Liverpool",
        market: "Match Result",
        selection: "Man City",
        odds: 1.85,
      },
    ],
    stake: 50,
    potentialWin: 92.5,
    status: "pending",
    placedAt: new Date(Date.now() - 1800000),
    bookingCode: "BB-8X7K2M",
  },
  {
    id: "b2",
    type: "multi",
    selections: [
      {
        id: "s2",
        matchId: "m2",
        matchName: "Real Madrid vs Barcelona",
        market: "Match Result",
        selection: "Real Madrid",
        odds: 2.10,
      },
      {
        id: "s3",
        matchId: "m4",
        matchName: "Bayern vs Dortmund",
        market: "Match Result",
        selection: "Bayern",
        odds: 1.65,
      },
    ],
    stake: 25,
    potentialWin: 86.63,
    status: "pending",
    placedAt: new Date(Date.now() - 3600000),
  },
];

export const mockTransactions: Transaction[] = [
  { id: "t1", type: "deposit", amount: 500, status: "completed", date: new Date(Date.now() - 86400000), method: "MTN Mobile Money" },
  { id: "t2", type: "withdrawal", amount: 200, status: "completed", date: new Date(Date.now() - 172800000), method: "Mobile Money" },
  { id: "t3", type: "deposit", amount: 100, status: "completed", date: new Date(Date.now() - 259200000), method: "Vodafone Cash" },
  { id: "t4", type: "withdrawal", amount: 150, status: "pending", date: new Date(Date.now() - 43200000), method: "Mobile Money" },
];

export const mockNotifications: Notification[] = [
  { id: "n1", title: "Bet Won!", message: "Your bet on Man City vs Arsenal won GH₵ 185.00", type: "success", read: false, date: new Date(Date.now() - 3600000) },
  { id: "n2", title: "New Promotion", message: "Weekend Live Boost - Enhanced odds on all live football", type: "promo", read: false, date: new Date(Date.now() - 7200000) },
  { id: "n3", title: "Deposit Confirmed", message: "Your deposit of GH₵ 500.00 has been processed", type: "info", read: true, date: new Date(Date.now() - 86400000) },
];

export const mockAdminStats: AdminStats = {
  totalUsers: 12847,
  activeUsers: 3421,
  totalDeposits: 2847650,
  totalWithdrawals: 1923400,
  totalBets: 89432,
  revenue: 924250,
};

export const heroSlides = [
  {
    id: "live-football",
    title: "Live Football Betting",
    subtitle: "Bet on Premier League, La Liga, Serie A, Bundesliga, and Champions League fixtures in real time.",
    cta: "View Live",
    badge: "LIVE",
    href: "/live",
    background: HERO_SLIDE_BACKGROUNDS.live,
    gradient: "from-bestbet-dark-secondary via-bestbet-gray to-bestbet-live/30",
  },
  {
    id: "top-leagues",
    title: "Top Leagues, Best Odds",
    subtitle: "Explore fixtures from Europe's biggest competitions and international friendlies on BestBet.",
    cta: "Browse Football",
    badge: "FOOTBALL",
    href: "/sports/football",
    background: HERO_SLIDE_BACKGROUNDS.leagues,
    gradient: "from-bestbet-dark via-bestbet-gray to-bestbet-yellow/20",
  },
  {
    id: "welcome-bonus",
    title: "Welcome Bonus",
    subtitle: "Double your first deposit up to GH₵ 500.00 and start betting on your favourite teams today.",
    cta: "Join Now",
    badge: "NEW",
    href: "/register",
    background: HERO_SLIDE_BACKGROUNDS.bonus,
    gradient: "from-bestbet-dark via-bestbet-yellow/10 to-bestbet-yellow-secondary/25",
  },
];

export const trendingBets = [
  { id: "tb1", selection: "Man City to Win", match: "Man City vs Liverpool", odds: 1.85, bets: 2847 },
  { id: "tb2", selection: "Over 2.5 Goals", match: "Real Madrid vs Barcelona", odds: 1.72, bets: 1923 },
  { id: "tb3", selection: "Arsenal to Win", match: "Arsenal vs Chelsea", odds: 2.05, bets: 1654 },
  { id: "tb4", selection: "Both Teams to Score", match: "Bayern vs Dortmund", odds: 1.65, bets: 1234 },
  { id: "tb5", selection: "Inter Milan ML", match: "Inter vs AC Milan", odds: 1.88, bets: 987 },
];
